default_stages: [commit, manual]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml # Checks yaml files for parseable syntax.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: check-json # Checks json files for parseable syntax.
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: requirements-txt-fixer # Sorts entries in requirements.txt
            exclude: "^kedro/templates/|^features/steps/test_starter/"
          - id: flake8
            args:
            - "--max-line-length=88"
            - "--max-complexity=18"
            - "--max-complexity=18"
            - "--select=B,C,E,F,W,T4,B9"
            - "--ignore=E203,E266,E501,W503"
            exclude: "^kedro/templates/|^features/steps/test_starter/"

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.961
      hooks:
          - id: mypy
            args: [--allow-redefinition, --ignore-missing-imports]
            exclude: |
                (?x)(
                  ^kedro/templates/|
                  ^docs/|
                  ^features/steps/test_starter/
                )
            additional_dependencies:
            - types-cachetools
            - types-filelock
            - types-PyYAML
            - types-redis
            - types-requests
            - types-setuptools
            - types-toml
            - attrs

    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            additional_dependencies: [black~=22.0]
            entry: blacken-docs --skip-errors

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.26.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]

    - repo: local
      hooks:
          - id: isort
            name: "Sort imports"
            language: system
            types: [file, python]
            exclude: ^kedro/templates/|^features/steps/test_starter
            entry: isort
          - id: black
            name: "Black"
            language: system
            files: ^kedro/|^features/|^tests/
            types: [file, python]
            exclude: ^features/steps/test_starter|^kedro/templates/
            entry: black

          # It's impossible to specify per-directory configuration, so we just run it many times.
          # https://github.com/PyCQA/pylint/issues/618
          # The first set of pylint checks if for local pre-commit, it only runs on the files changed.
          - id: pylint-quick-kedro
            name: "Quick Pylint on kedro/*"
            language: system
            types: [file, python]
            files: ^kedro/
            exclude: ^kedro/templates/
            entry: pylint -j 4 --disable=unnecessary-pass
            stages: [commit]
          - id: pylint-quick-features
            name: "Quick Pylint on features/*"
            language: system
            types: [file, python]
            files: ^features/
            exclude: ^features/steps/test_starter
            entry: pylint -j 4 --disable=missing-docstring,no-name-in-module
            stages: [commit]
          - id: pylint-quick-tests
            name: "Quick Pylint on tests/*"
            language: system
            types: [file, python]
            files: ^tests/
            entry: pylint -j 4 --disable=missing-docstring,redefined-outer-name,no-self-use,invalid-name,protected-access,too-many-arguments,too-many-public-methods
            stages: [commit]

          # The same pylint checks, but running on all files. It's for manual run with `make lint`
          - id: pylint-kedro
            name: "Pylint on kedro/*"
            language: system
            pass_filenames: false
            stages: [manual]
            entry: pylint -j 4 --disable=unnecessary-pass --init-hook="import sys; sys.setrecursionlimit(2000)" kedro
          - id: pylint-features
            name: "Pylint on features/*"
            language: system
            pass_filenames: false
            stages: [manual]
            exclude: ^features/steps/test_starter
            entry: pylint -j 4 --disable=missing-docstring,no-name-in-module features
          - id: pylint-tests
            name: "Pylint on tests/*"
            language: system
            pass_filenames: false
            stages: [manual]
            entry: pylint -j 4 --disable=missing-docstring,redefined-outer-name,no-self-use,invalid-name,protected-access,too-many-arguments,too-many-public-methods,use-implicit-booleaness-not-comparison tests
